//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RTSDBEntities : DbContext
    {
        public RTSDBEntities()
            : base("name=RTSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<accountDetail> accountDetails { get; set; }
        public virtual DbSet<AFI> AFIs { get; set; }
        public virtual DbSet<appUser> appUsers { get; set; }
        public virtual DbSet<SubDivision> SubDivisions { get; set; }
        public virtual DbSet<Town> Towns { get; set; }
        public virtual DbSet<Ward> Wards { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<accountStatu> accountStatus { get; set; }
    }
}
