//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.accountDetails = new HashSet<accountDetail>();
        }
    
        public int Id { get; set; }
        public string title { get; set; }
        public int amount_due { get; set; }
        public string status { get; set; }
        public double longitude { get; set; }
        public double latitude { get; set; }
        public int Ward_Id { get; set; }
        public string address { get; set; }
        public int walk_sort { get; set; }
        public int property_no { get; set; }

       
        public virtual Ward Ward { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accountDetail> accountDetails { get; set; }
    }
}
