//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appUser
    {
        public int id { get; set; }
        public string ticket { get; set; }
        public string password { get; set; }
        public string role { get; set; }
        public Nullable<int> afi_id { get; set; }
        public Nullable<int> rfi_id { get; set; }
    
        public virtual AFI AFI { get; set; }
    }
}
