//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConSummary
    {
        public int id { get; set; }
        public System.DateTime entrdate { get; set; }
        public int townid { get; set; }
        public int domestic { get; set; }
        public int commercial { get; set; }
        public int cheritable { get; set; }
        public int reading { get; set; }
        public int average { get; set; }
        public int water { get; set; }
        public int sewer { get; set; }
        public int water_and_sewer { get; set; }
        public int aquifer_water { get; set; }
        public int aquifer_sewer { get; set; }
    
        public virtual Town Town { get; set; }
    }
}
