//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefaulterPayment
    {
        public int accountNo { get; set; }
        public int townId { get; set; }
        public int arears { get; set; }
        public int amountRecieved { get; set; }
    
        public virtual Town Town { get; set; }
    }
}
