//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecoveryProgress
    {
        public int id { get; set; }
        public int month { get; set; }
        public int year { get; set; }
        public bool isComplete { get; set; }
        public int target { get; set; }
        public int recovered { get; set; }
        public int NCR { get; set; }
        public int UCR { get; set; }
        public int MisUse { get; set; }
        public int townId { get; set; }
        public int accountPaid { get; set; }
    
        public virtual Town Town { get; set; }
    }
}
